language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  #- "nightly"
# we force update dev_requirements.txt so we get latest master of selinonlib to
# be consistent with test
install: 
  - pip3 install -r requirements.txt 
  - pip3 install -U -r dev_requirements.txt
  - pip3 install -U coala-bears
script: make check
after_success:
  - bash <(curl -s https://codecov.io/bash)
